#!/bin/bash
#
# Import from https://github.com/KYG-yaya573142/fibdrv/blob/master/do_measurement.sh
#
#This script tweak the system setting to minimize the unstable factors while
#analyzing the performance of fibdrv.
#
#2020/3/21  ver 1.0
CPUID=1
ORIG_ASLR=`cat /proc/sys/kernel/randomize_va_space`
ORIG_GOV=`cat /sys/devices/system/cpu/cpu$CPUID/cpufreq/scaling_governor`
ORIG_TURBO=`cat /sys/devices/system/cpu/intel_pstate/no_turbo`

sudo bash -c "echo 0 > /proc/sys/kernel/randomize_va_space"
sudo bash -c "echo performance > /sys/devices/system/cpu/cpu$CPUID/cpufreq/scaling_governor"
sudo bash -c "echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo"

#measure the performance of fibdrv
make
make unload
make load
sudo taskset -c $CPUID ./exp 0 > fib.csv
sudo taskset -c $CPUID ./exp 1 > fast.csv
gnuplot time_plot.gp
sudo perf stat -r 10 -e cycles,instructions,cache-misses,cache-references,branch-instructions,branch-misses taskset -c $CPUID ./exp 1 > /dev/null
# restore the original system settings
sudo bash -c "echo $ORIG_ASLR >  /proc/sys/kernel/randomize_va_space"
sudo bash -c "echo $ORIG_GOV > /sys/devices/system/cpu/cpu$CPUID/cpufreq/scaling_governor"
sudo bash -c "echo $ORIG_TURBO > /sys/devices/system/cpu/intel_pstate/no_turbo"